### ISSUE TITLE
Support Markdown for readmes

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#148]
Originally reported by: **Hickford (Bitbucket: [hickford](https://bitbucket.org/hickford), GitHub: [hickford](https://github.com/hickford))**

---

If you write your readme in Restructured Text, PyPI will render it on your project's page (eg. https://pypi.python.org/pypi/requests ). It should be possible to write your readme in Markdown too. Markdown is a pervasive format used on GitHub and StackOverflow. It shouldn't be necessary to learn a new markup language or rewrite your project's documentation to publish a Python package.

This is common frustration. The Python community suffers because it's a barrier to publishing packages and writing documentation . Please consider supporting Markdown!
- http://stackoverflow.com/questions/10718767/have-the-same-readme-both-in-markdown-and-restructuredtext
- http://i.imgur.com/7NYlimN.png
- https://coderwall.com/p/qawuyq

---

**Update 2014**: Here's a pull request! https://bitbucket.org/pypa/pypi/pull-request/59/support-markdown-for-readmes-fixes-148/diff

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/148

**Comment by femtotrader** [comment]
Some people don't like this solution
See discussion here https://github.com/femtotrader/pandas_talib/issues/8

**Comment by nchammas** [comment]
@femtotrader - If by "this solution" you are referring to [my suggestion just above](https://github.com/pypa/pypi-legacy/issues/148#issuecomment-226939424), I don't see how it is a problem.

The users in the discussion you linked to are complaining that they have to install Pandoc just to install your library. However, at the end of my comment I noted:

> It's straightforward and should work for most projects. You can add a fallback like in the Stack Overflow answer I linked to so that people running python setup.py without pandoc installed will get the plain Markdown README.

In other words, only the maintainer who is uploading a package to PyPI will need Pandoc installed.

Perhaps I should have included that in my code sample, rather than just referring to it on Stack Overflow via a link. But to spell things out, if you have something like this in your `setup.py`:

```python
try:
    import pypandoc
    long_description = pypandoc.convert('README.md', 'rst')
except ImportError:
    long_description = open('README.md').read()
```

And then you have Pandoc listed as a separate requirement only for maintainers, perhaps in a `maintainer.pip` file, then you get what you want. Users aren't burdened installing a package they don't need, and maintainers get their README in RST without having to learn that format just for PyPI.

That's how I do it in my project:
* [`setup.py`](https://github.com/nchammas/flintrock/blob/b41861bcb6bee22799a547c6db503c941a819728/setup.py#L3-L7)
* [`maintainer.pip`](https://github.com/nchammas/flintrock/blob/b41861bcb6bee22799a547c6db503c941a819728/requirements/maintainer.pip)

It's not the solution we all ultimately want, but I think it's good enough for the time being.

**Comment by femtotrader** [comment]
I understand this correctly. Sorry for being not clear enough...
I really think that solution is to render correctly Markdown on server side.

**Comment by mec07** [comment]
I also think pypi should just support markdown.

**Comment by berkerpeksag** [comment]
Since this is a new feature and implementing it is not easy as calling `markdown.markdown(long_description)` in legacy PyPI and there is already [an open issue in Warehouse's issue tracker](https://github.com/pypa/warehouse/issues/869), I'm going to close this one. Thank you all for the discussion!
