### ISSUE TITLE
Add "Framework :: AsyncIO" as trove classifier

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#257]
Originally reported by: **Ludovic Gasc (Bitbucket: [gmludo](https://bitbucket.org/gmludo), GitHub: [gmludo](https://github.com/gmludo))**

----------------------------------------

Hi,

In trove classifier: https://pypi.python.org/pypi?%3Aaction=list_classifiers , you have several ecosystems classifiers like "Framework :: Django" but also "Framework :: Twisted" and "Framework :: IPython".

It should be interesting to add "Framework :: AsyncIO" classifier, because you already have several librairies based on AsyncIO: https://code.google.com/p/tulip/wiki/ThirdParty

Regards.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/257

**Comment by GMLudo** [comment]
@piotrjurkiewicz: async/await introduction doesn't mean the end of asyncio module, it's the contrary because it means that AsyncIO becomes a first class citizen in Python.

AsyncIO ecosystem continues to grow: https://github.com/python/asyncio/wiki/ThirdParty

To me, the trover classifier should be added.

If I do a pull request to update this SQL file: https://github.com/pypa/pypi-legacy/blob/86f65dce25786c7832f5ae45ee44666826669621/pkgbase_schema.sql#L2287
Is it enough, or it's necessary to do something else ?

**Comment by berkerpeksag** [comment]
Per https://github.com/pypa/pypi-legacy/issues/301#issuecomment-226940147, this needs to be reported to https://github.com/pypa/warehouse now.
