### ISSUE TITLE
The admonitions are not rendered properly on pypi/warehouse

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#303]
Originally reported by: **Raffi Enficiaud (Bitbucket: [renficiaud](https://bitbucket.org/renficiaud), GitHub: Unknown)**

----------------------------------------

When I use 

```
#!rest
.. note::

```

or 

```
#!rest
.. warning::
```

I get something that looks like a title instead.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/303

**Comment by berkerpeksag** [comment]
I think what you are referring to is can be seen at https://pypi.python.org/pypi/murl (see the "Getting Started" section) This can easily be fixed with CSS but we need to alter the markup (it just a plain `<div>` at the moment). AFAIK, both PyPI and Warehouse use https://github.com/pypa/readme_renderer and this needs to be fixed there first.
