### ISSUE TITLE
pip reporting could not find a version that satisfies the requirement pysphere==0.1.8

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#376]
Originally reported by: **Robert McQueen (Bitbucket: [robert_mcqueen](https://bitbucket.org/robert_mcqueen), GitHub: Unknown)**
---

Could not find a version that satisfies the requirement pysphere==0.1.8 (from versions: 0.1.0, 0.1.5, 0.1.6, 0.1.7)

https://pypi.python.org/pypi/pysphere

The latest version has been available as 0.1.8 for over a year.  However, it is unable to be downloaded using pip or easy_install.
---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/376

**Comment by berkerpeksag** [comment]
Thanks for the report. That's because 0.1.7 is the last release that was uploaded to PyPI. 0.1.8 only has the "Download URL" field set to http://pysphere.googlecode.com/files/pysphere-0.1.8.zip, but it doesn't have a sdist or any other files. PyPI/pip doesn't support installing of externally hosted packages anymore. You can compare https://pypi.python.org/pypi/pysphere/0.1.8 with https://pypi.python.org/pypi/pysphere/0.1.7 (see pysphere-0.1.7.win32.exe and pysphere-0.1.7.zip)
