### ISSUE TITLE
Sploitego Links missing from simple

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#435]
Originally reported by: **John (Bitbucket: [spoclate](https://bitbucket.org/spoclate), GitHub: Unknown)**

----------------------------------------

easy_install sploitego not working as link are missing from https://pypi.python.org/simple/sploitego/

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/435

**Comment by berkerpeksag** [comment]
It didn't worked before because of [PEP 470](https://www.python.org/dev/peps/pep-0470/). I can now see `sploitego-1.2.2.tar.gz` at https://pypi.python.org/simple/sploitego/ as its maintainer has been uploaded `sploitego-1.2.2.tar.gz` on 2016-04-28. Confirmed by running both `easy_install sploitego` and `pip install sploitego` commands.
