### ISSUE TITLE
Download statistics missing

### ISSUE THREAD

**Issue by mahmoud** [pypa/pypi-legacy#484]
Maybe I missed an email about this, but I noticed the download statistics disappeared from PyPI a couple months ago, and they're yet to return. The numbers themselves are available on Warehouse, but they're amongst a bunch of TODO stuff that makes it kind of unsuitable for presenting to wider audiences.

Just to be clear, I'm referring to when PyPI looked like:

![boltons_pypi_nov2015](https://cloud.githubusercontent.com/assets/130193/17002678/4b68f512-4e81-11e6-937b-170aa6ed8857.png)

Thanks!

**Comment by ewdurbin** [comment]
stats for downloads in warehouse are now powered by https://github.com/pypa/linehaul, unfortunately in order to support this, stats for legacy pypi needed to be deprecated.

there are no plans to restore this functionality before the launch of warehouse as the "real" pypi.

currently, aside from warehouse, stats and a *whole* lot of other interesting data can now be queried by anyone with a Google account. see https://mail.python.org/pipermail/distutils-sig/2016-May/028986.html

i'm currently working on getting access for the wiki regarding developer resources and things like this. sorry for the "look at this mailing list archive" in the meantime.

**Comment by mahmoud** [comment]
Oh, no, I saw that email. Saw it the day you sent it. Maybe I'm missing something, but I didn't read it as a permanent removal of statistics from PyPI. For mature projects, deprecation is a process that usually involves a timeline. Easy-to-access statistics are important to me and my students, so I've created issue #485 to discuss possible solutions.
