### ISSUE TITLE
Unable to find owner of package with no releases

### ISSUE THREAD

**Issue by reversefold** [pypa/pypi-legacy#531]
I have created a new open source project called shinkansen but when trying to upload it to pypi I get an error about being unauthorized. Searching the site gives no results. I'd like to contact the current "owner" of the name to see if it can be transferred or, failing that, to lay claim to it if it has never been used.

Is any of this possible or do I need to come up with a new package name for pypi?

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
