### ISSUE TITLE
width tag not respected for images

### ISSUE THREAD

**Issue by nschloe** [pypa/pypi-legacy#547]
When including images like
```rst
.. figure:: https://nschloe.github.io/quadrature/circle.svg
   :alt: 
   :width: 25.0%
```
the `width` tag is not respected. See, e.g., [here](https://pypi.python.org/pypi/quadrature).

**Comment by Carreau** [comment]
Hi there, 

I would recommend opening the issue on the [warehouse repo](https://github.com/pypa/warehouse/issues) as it is ment to replace PyPI-legacy which is on maintnance mode until replaced. Maintainers are more active there than here. You can see that your issue is still visible when looking at [your package on warehouse](https://pypi.org/project/quadrature/), but the warehouse codebase is easier to work with and have unit-testing which would ensure this is : 
  - fixed, 
  - say fixed. 

Warehouse is also much easier to run locally if you want to try submitting a PR. 

Thanks !

**Comment by di** [comment]
[The `readme_renderer` repo](https://github.com/pypa/readme_renderer/) would be a more appropriate place for this issue--it's what Warehouse uses to render READMEs into HTML.

**Comment by Carreau** [comment]
> The readme_renderer repo would be a more appropriate place for this issue--it's what Warehouse uses to render READMEs into HTML.

Indeed, thanks for pointing that out !

**Comment by berkerpeksag** [comment]
Thank you for the report. I'm closing this one as an issue against pypa/readme_renderer repository has already been opened: https://github.com/pypa/readme_renderer/issues/44
