### ISSUE TITLE
Can't upload (wrong password)

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#56]
Originally reported by: **smontanaro (Bitbucket: [smontanaro](https://bitbucket.org/smontanaro), GitHub: [smontanaro](https://github.com/smontanaro))**

---

I'm trying to upload a distribution, but it complains:

Upload failed (401): Incorrect password

I checked the password in ~/.pypirc.  It is the same as the password I used to log into pypi.python.org.  What am I doing wrong?

---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/56

**Comment by jndoye** [comment]
Hi,
I am having the same issue when my pypirc seems valid with username and password and my registration is ok since I can login in https://testpypi.python.org/pypi and https://pypi.python.org/pypi.
Anyone could help please?

Logs:
running register
running egg_info
writing virtualPyTest.egg-info\PKG-INFO
writing top-level names to virtualPyTest.egg-info\top_level.txt
writing dependency_links to virtualPyTest.egg-info\dependency_links.txt
reading manifest file 'virtualPyTest.egg-info\SOURCES.txt'
writing manifest file 'virtualPyTest.egg-info\SOURCES.txt'
running check
warning: check: Could not finish the parsing.
Registering virtualPyTest to https://testpypi.python.org/pypi
Server response (401): basic auth failed

**Comment by di** [comment]
This is resolved as far as I can tell. Uploads are now done through `pypi.org`, anyone still having problems should open a new issue at https://github.com/pypa/warehouse/issues.
