### ISSUE TITLE
Pypi single-letter queries 's' 'c' 'i' ... don't find 'scicfg'

### ISSUE THREAD

**Issue by denis-bz** [pypa/pypi-legacy#575]
Pypi single-letter queries 's' 'c' 'i' ... don't find 'scicfg',
neither with xmlrpclib.ServerProxy nor with `pip search`.
A little `test-pypi-short-search.py` is under https://gist.github.com/denis-bz
with .log

    # pypi.search substrings of "scicfg"
    s     :  5824 hits
    ? scicfg not found
    c     :  5805 hits
    ? scicfg not found
    i     :  5817 hits
    ? scicfg not found
    c     :  5805 hits
    ? scicfg not found
    f     :  5816 hits
    ? scicfg not found
    g     :  5807 hits
    ? scicfg not found

2-letter and longer substrings are ok.
Odd that these are all around 5800 long ?
    
Versions: python 2.7.12   mac 10.8.3

Thanks, cheers
  -- denis

**Comment by ewdurbin** [comment]
@denis-bz we use elastic search for search in legacy pypi, and limit the result count.

single character queries would generate result sets that are too long for use to efficiently serve without causing issues on the backends.

this won't be fixed in legacy pypi, if the same behavior is noted with https://pypi.org's search please file an issue with pypa/warehouse.
