### ISSUE TITLE
pypi.python.org does not properly render rst readmes

### ISSUE THREAD

**Issue by AraHaan** [pypa/pypi-legacy#619]
So, I have a package on pypi.python.org that takes in an rst readme that I had to convert manually from markdown) Because pypi.python.org does not render md files as well...

However it still does not render them for some reason. But aiohttp's does render how I want...

mine: https://pypi.python.org/pypi/discord.webhooks
aiohttp's: https://pypi.python.org/pypi/aiohttp

I also tried to ask asvetlov exactly how they got it to work but got no reply. The thing that I would like is if pypi.python.org was to use github's markup library or something to render the readmes on pypi that would be absolutely awesome if that was to happen. Unfortunately that would mean github would have to make a version of it in pure python.

**Comment by di** [comment]
@AraHaan You can use https://github.com/pypa/readme_renderer to check your `long_description` locally before submitting to PyPI (see [here](https://github.com/pypa/readme_renderer#check-description-locally) for instructions).

In the case of your `discord.webhooks` project, the issue seems to be that you're attempting to use the `cmd` pygments lexer, which doesn't exist. Try changing it to `sh` instead.

**Comment by AraHaan** [comment]
ah, thanks. I did not know ``cmd`` was not in the pygments lexer.
