### ISSUE TITLE
There is nothing behind the pymeter project

### ISSUE THREAD

**Issue by GeorgeFischhof** [pypa/pypi-legacy#635]
Hi There,

There is nothing behind the pymeter project: no webpage, no downloadable, no package.
I do not know what is the normal workflow for this kind of issues, but I think the package shouold be removed from package index.

BR,
George

**Comment by berkerpeksag** [comment]
I think PEP 541 will help resolving issues such as this when it's ready. See "Abandoned projects" section at https://www.python.org/dev/peps/pep-0541/#abandoned-projects for details.

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
