### ISSUE TITLE
Multiple libarchive packages

### ISSUE THREAD

**Issue by alevesely** [pypa/pypi-legacy#645]
The statement

    import libarchive

is not clear.  It can refer to either libarchive-c[1] or libarchive[2].  Names are not preserved, so that after `pip install libarchive-c`, the command `pip install libarchive` reports it's already installed and invites to upgrade it.  This situation is confusing and requires strict coordination among maintainers of a given (virtual) environment, not quite what one would expect of an automated package manager.

[1] https://github.com/Changaco/python-libarchive-c
[2] https://github.com/smartfile/python-libarchive

**Comment by jamadden** [comment]
What bug are you suggesting exists in pypi-legacy (the software that runs pypi.python.org to facilitate uploading, finding and downloading python distributions, and the topic this issue tracker is for)? 

It's a fact that Python packaging makes a distinction between "distributions" ([or "libraries"](https://caremad.io/posts/2013/07/setup-vs-requirement/)) and "importable packages." A distribution is an archive uploaded to PyPI and installed by pip. 

A distribution can provide *multiple* importable packages. For example, ZODB3 provides the 'persistent', 'transaction', 'BTrees' and 'ZODB' packages. 

Likewise, different distributions can provide packages with the same name. Apparently `libarchive` and `libarchive-c` is an example: two implementations with different requirements and performance characteristics (I'm guessing). Another example is `sphinxcontrib-programoutput` and `nti.sphinxcontrib-programoutput`, the latter of which arose due to a fork after maintenance stopped on the former; I'm sure there are more such examples. 

All of these examples can be seen as an important feature of the packaging ecosystem.

If you feel that this model needs changes, this issue tracker is not the place to discuss them. I suggest the [distutils-sig](https://mail.python.org/mailman/listinfo/distutils-sig) mailing list.

**Comment by alevesely** [comment]
I thought it was a point of the packaging system to avoid name conflicts.
Thank for the clarification.  I think the issue can be closed now.

**Comment by rjkmurray** [comment]
Lol, OK but remember that some pips do mixs 

Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Alessandro Vesely <notifications@github.com> Date: 2017-05-29  4:53 AM  (GMT-03:30) To: pypa/pypi-legacy <pypi-legacy@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [pypa/pypi-legacy] Multiple libarchive packages (#645) 
I thought it was a point of the packaging system to avoid name conflicts.

Thank for the clarification.  I think the issue can be closed now.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pypa/pypi-legacy","title":"pypa/pypi-legacy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pypa/pypi-legacy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alevesely in #645: I thought it was a point of the packaging system to avoid name conflicts.\r\nThank for the clarification.  I think the issue can be closed now."}],"action":{"name":"View Issue","url":"https://github.com/pypa/pypi-legacy/issues/645#issuecomment-304591476"}}}
