### ISSUE TITLE
Claim package fixlib

### ISSUE THREAD

**Issue by djc** [pypa/pypi-legacy#650]
I would like to reclaim the fixlib package (from user "kentyde", for user "djc").

I was the original author of this package, and it was open source by my employer under the MIT license. My employer is shutting down; the work email address I used to register the account is no longer routable, and I forgot the password on the account. The package metadata lists my name and my work email address. I do retain control of the original Bitbucket repository, but the homepage on PyPI lists an address on Bitbucket using a CNAME from the company domain, which is also no longer functioning.

Filed on the SourceForge issue tracker 18 months ago: https://sourceforge.net/p/pypi/support-requests/588/

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
