### ISSUE TITLE
claim 'pyparted' entry on pypi.python.org

### ISSUE THREAD

**Issue by dcantrell** [pypa/pypi-legacy#654]
Someone uploaded one of my releases to pypi, but it wasn't me.  I am the author and maintainer of pyparted and would like to release it on pypi.  But I am unable to upload a new version.

**Comment by jamadden** [comment]
I've reached out to the email address listed in the AUTHORS file for the pyparted tarball [hosted on PyPI](https://pypi.python.org/packages/2c/a9/69f67f6d5d2fd80ef3d60dc5bef4971d837dc741be0d53295d3aabb5ec7f/pyparted-3.10.7.tar.gz#md5=79ac5dd99eb32a8572e0c79eb4241664) to try to confirm identities.

**Comment by jamadden** [comment]
I received a reply from the email address listed in the AUTHORS file confirming that it is indeed @dcantrell.

**Comment by brainwane** [comment]
@dcantrell  I'm sorry for the wait. I'm responding here in case this was not resolved in 2017.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
