### ISSUE TITLE
Becoming owner of unmaintained winpdb package

### ISSUE THREAD

**Issue by bluebird75** [pypa/pypi-legacy#657]
Hi,

This is a request related to a specific PyPI package, please tell me if there is a more appropriate medium to put my request.

My request is related to the project page of Winpdb, a standalone portable WxPython debugger. It has been developed by Nir Aides, initially on google code. See ( http://www.winpdb.org and  https://pypi.python.org/pypi/winpdb ). The last release of winpdb is version 1.4.8, in 2010.

Since 2013, I have been maintaining a bug-fixed version on Github, which fixes a few annoying bugs, removes a few annoyances and provides more compatibility with latest versions of Python. A kind of a friendly fork, which I properly refernce the history of the project.

In 2014, I exchanged a few emails with Nir Aides, the author, to have my version reviewed and possibly published. Unfortunately this never happened, despite several reminders.

This could have been fine, but lately, with google code shutdown, the packaged version on PyPi no longer works: it pulls a previous buggy version of winpdb due to dead google code links (see https://github.com/bluebird75/winpdb/issues/6 ). 

My attempt to contact the author to fix this issue have been unanswered.

I therefore would like to become the de facto author on the PyPi page, in order to fix the issue above, and even release the latest bugfixed version.

Thanks in advance for your support.

Cheers,

Philippe

**Comment by jamadden** [comment]
Have you considered uploading your fork with a different name? Unless you can *also* get access to `www.winpdb.org` that might be slightly less confusing given that all of its links and info will be outdated worse than they are now. (And if you *can* get control of the domain, well, I guess this problem is probably also solved by that point.)

**Comment by bluebird75** [comment]
I have considered creating a fork with a similar name but this should be the last resort. Since the current winpdb is abandoned, becoming a new maintainer would be a better path.

A search for winpdb on google yields first www.winpdb.org, second the pypi project page and third my maintained version at Github. I consider that somebody looking for latest winpdb will find my version pretty easily. Even more easily if I become owner of the pypi package :-) as I am asking.

I don't intend to take over www.winpdb.org . When the last news on the site is from 2010, it's pretty clear that the site is unmaintained. 

On the short term, if you could adjust the download link from  http://winpdb.googlecode.com/files/winpdb-1.4.8.tar.gz to https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/winpdb/winpdb-1.4.8.tar.gz that would be nice.

On the long term, if I can become owner without the previous owner's approval, that's great. If not I will have to create an official fork, the owner being unresponsive so far.

**Comment by bluebird75** [comment]
Any news ?

**Comment by bluebird75** [comment]
Hi,

I have read [PEP0541](https://www.python.org/dev/peps/pep-0541/) thoroughly and the situation I am in fits perfectly with the chapter _Continued maintenance of an abandoned project_ .

How do I engage the process of continued maintenance ? Should I contact the  distutils-sig ?

**Comment by brainwane** [comment]
@bluebird75 I'm sorry for the wait. We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers, including yours. Until then, unfortunately, all I can advise you to do is wait.

**Comment by bluebird75** [comment]
Thanks for the feedback. I'll wait then...

**Comment by brainwane** [comment]
Again, @bluebird75, I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

Once we resolve https://github.com/pypa/warehouse/issues/1506 , we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

And my continued apologies for the delay.
