### ISSUE TITLE
https://pypi.python.org/simple/gnuplot-py/ has no entries

### ISSUE THREAD

**Issue by karotak** [pypa/pypi-legacy#688]
First of all I'm new to python.
I tried to "pip install gnuplot-py" but pip aborted with:
"Could not find a version that satisfies the requirement gnuplot-py (from versions: ) No matching distribution found for gnuplot-py".
Therefore I checked the aforementioned url and noticed the page doesn't contain any links.

Now I'm confused. Is this a error? If not am I missing something or why is gnuplot-py indexed but not installable with pip?

**Comment by jamadden** [comment]
From looking at [the PyPI page for gnuplot-py](https://pypi.python.org/pypi/gnuplot-py), it appears that this distribution has *not* uploaded any distributions (tarballs, binary wheels, etc) to PyPI. Instead, it has just provided an external "Download URL."

In the past, that was a supported way to install packages from PyPI. Now, however, pip/PyPI requires that the distribution files actually be uploaded to PyPI; it no longer tries to find external URLs to download from. This change was due to security concerns, IIRC.

You can still download the distribution file manually from the Download URL and then `pip install /the/path/to/the/file.tar.gz`, I believe, though.

**Comment by jamadden** [comment]
I'm going to go ahead and close this since it doesn't appear to be a pypi-legacy issue. Thanks for the report!
