### ISSUE TITLE
Claim package iap_local_receipt

### ISSUE THREAD

**Issue by efine** [pypa/pypi-legacy#690]
(This was initially reported on the [Support Forum][1]).

I am the author of the `iap_local_receipt` package on GitHub ([SilentCircle/iap_local_receipt][2]) and [PyPI][4].

The PyPI login credentials of the package index owner (`silentcircle`) are lost. Sadly, due to email domain changes at the company, and possibly staff turnover, any associated email addresses PyPI might have probably won't work - I tried requesting password reset emails, and nobody I spoke to at Silent Circle seemed to get one. Now there are updates to the package and I can't upload the new version to PyPI, which has been requested by a user (see [issue][3]).

My (working!) email address is in the `PKG_INFO` file - would it be possible to send a password change email to that address? Or to change the owner to me?

Any help much appreciated.

[1]: https://sourceforge.net/p/pypi/support-requests/746/
[2]: https://github.com/SilentCircle/iap-local-receipt
[3]: https://github.com/SilentCircle/iap-local-receipt/issues/4
[4]: https://pypi.python.org/pypi/iap_local_receipt

**Comment by efine** [comment]
Just checking in. Should I give up on this package and upload it under a different name and package? That would be a last resort, and it contributes to the typosquatting issue, but there seems to be no ETA on this, so your thoughts (any response, really) would be very helpful at this point.

**Comment by ewdurbin** [comment]
Given that the project owner has an email address on a domain which appears to be gone but is obviously associated with SilentCircle, It would be most direct to transfer the project to a user registered and confirmed with an email address on their new domain (silentcircle.com). From there, managing owner/mantainer roles in pypi would be preferred rather than changing the package owner.

An alternative is for someone to email ernest@python.org from an @silentcircle.com email address confirming that they would like to have the user silentcircle changed to a specific address on that domain at which point a password reset would be issued allowing them to access the user on PyPI.

**Comment by efine** [comment]
@ernest, thank you. I've emailed you with the details you require.

**Comment by ewdurbin** [comment]
@efine I have not seen anything come through. can you confirm you sent to the correct email?

**Comment by ewdurbin** [comment]
resolved
