### ISSUE TITLE
Unable to upload to project called "mu"

### ISSUE THREAD

**Issue by ntoll** [pypa/pypi-legacy#705]
Hi,

I've written a code editor called Mu. See: https://github.com/mu-editor/mu Over the summer I've been supported by the Raspberry Pi Foundation to get Mu to 1.0. It's almost there and I'd like to make it installable via PyPI.

As far as I can tell, `mu` isn't a registered name. Unfortunately, if I try to `pip install mu` I get the following:

```
$ pip install mu
Collecting mu
  Could not find a version that satisfies the requirement mu (from versions: )
No matching distribution found for mu
```

Furthermore, I get a 404 from http://pypi.python.org/ if I try visit where the package's page should be (https://pypi.python.org/pypi/mu).

If I try to submit the package I get:

```
Submitting dist/mu-1.0.0b6.tar.gz to https://upload.pypi.org/legacy/
Upload failed (403): The user 'ntoll' is not allowed to upload to project 'mu'. See https://pypi.org/help#project-name for more information.
error: Upload failed (403): The user 'ntoll' is not allowed to upload to project 'mu'. See https://pypi.org/help#project-name for more information.
```

The three requirements about invalid names don't appear to apply:

* `mu` isn't in the standard library,
* `mu` seems innocuous enough to NOT be on the excluded names list,
* If it's created by another user, I should be able to see the web page for it.

My username on pypi is `ntoll`. Would love to know what the problem is (for example, is there a minimum length limit on names?). Alternatively, is this a bug? Finally, if possible, how do I register and upload my `mu` package?

Happy to help in any way that I can. If you need more information just ask..!

Thanks in advance.

**Comment by jamadden** [comment]
There *is* an entry for `mu` in the index:
```
$ http https://pypi.python.org/simple/ | grep \'mu\'
<a href='mu'>mu</a><br/>
``` 

but it currently has no links:
```
$ http https://pypi.python.org/simple/mu/
HTTP/1.1 200 OK
...
<!DOCTYPE html><html><head><title>Links for mu</title></head><body><h1>Links for mu</h1></body></html>
```

Compared to a package that's not in the index:
```
$ http https://pypi.python.org/simple/mu2/
HTTP/1.1 404 Not Found (mu2 does not exist)
...

Not Found (mu2 does not exist)
```

So at some point at least `mu` was a registered project. I'm not sure why the project page 404s though.

**Comment by ntoll** [comment]
@jamadden aha! Thank you for looking into this. Given that it appears to have once been a registered project, can I ask that it be put "back in the pool" and then I can actually use it for something useful..? :-)

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
