### ISSUE TITLE
Transfer ownership of aggdraw package

### ISSUE THREAD

**Issue by djhoese** [pypa/pypi-legacy#714]
I posted this request on the sourceforge repository first because I didn't know this repository existed: https://sourceforge.net/p/pypi/support-requests/763/

The aggdraw package has not been updated since 2005 (based on current package name). I have attempted to contact the current owner (effbot - Fredrik Lundh) through a couple emails I found online, but have not received a response after about a month. Would it be possible to transfer ownership to me.

The project has been forked by many and has lived on github for a while. Recently the "pytroll" open source group took over maintainership of the most popular fork and added python 3 compatibility. The repository can be found here: https://github.com/pytroll/aggdraw

Thanks.

**Comment by a-hurst** [comment]
I also think it's worthwhile pointing out that the aggdraw module that currently lives on PyPi does not install at all with pip on newer (e.g. 64-bit) platforms, so people wanting to run older projects that rely on it currently have no choice but to install it from source. Thus, it's not just a question of updating an old package so its features are current, it's a question of updating a package so it works at all (for most people). 

In addition, I believe that taking over the existing package is a better solution than creating a new package with a different name because it will create less confusion for people trying to install aggdraw as a dependency for old code. As such, I feel as though this case satisfies the criteria for "continued maintenance of an abandoned project" laid out in [PEP 541](https://www.python.org/dev/peps/pep-0541/).

I currently maintain a project that depends on aggdraw and being able to install it directly from pip would make my life a lot easier.

**Comment by davidh-ssec** [comment]
Just in case there is a chance...ping @effbot. Is this the real effbot that created aggdraw?

**Comment by PythonCHB** [comment]
It would be great to have aggdraw available and easy to find! Especially if you build binary wheels for the major platforms.

But while waiting, why not create an aggdraw2 or something pypi package and get rolling.

people looking for aggdraw would certainly find it.

Another option would be to simply include it with PIllow -- it's really nicer than the "build in" drawing code.

**Comment by PythonCHB** [comment]
If you heard from effBot, then great, that's definitely the best solution.

Let me know if you need help with conda-forge, I'd be interested in getting this out there, too.

You may want to reach out to the MAcPython wheels folks:

https://github.com/MacPython/wiki/wiki/Spinning-wheels

They are also doing Windows (and manylinux?) and have set up a conda-forge-ish infrastructure for building compiled binary wheels (and some with the same deps as pillow).

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
