### ISSUE TITLE
transfer ownership of package pycairo to @lazka

### ISSUE THREAD

**Issue by stuaxo** [pypa/pypi-legacy#726]
This is a copy of the ticket from sourceforge https://sourceforge.net/p/pypi/support-requests/728/

Please add @lazka https://pypi.org/user/lazka to the owners list.

Current state:

*    The name does not contains any source/binary packages
*    The owning user "stevech1097" can't be contacted. The email
    (stevech1097@yahoo.com.au) bounces and to my knowledge there exists no
    alternative channel for communication. The same email is used upstream.
*    https://www.cairographics.org/pycairo/ now points to
    https://github.com/pygobject/pycairo
*    I've created a branch there to connect the repo with my pypi user name:
    https://github.com/pygobject/pycairo/blob/pypi-change/pypi-owner-change.txt

thanks

**Comment by ewdurbin** [comment]
It appears that the pycairo project on PyPI predates the deprecation of external release hosting and never made the move to hosting on PyPI. Three releases exist, only one with one of the "old style" external download urls:

```
  name   | version |                      download_url                      
---------+---------+--------------------------------------------------------
 pycairo | 1.10.0  | 
 pycairo | 1.8.10  | 
 pycairo | 1.8.8   | http://cairographics.org/releases/pycairo-1.8.8.tar.gz
```

This seems like a reasonable request.

I've emailed the email address on file for the PyPI user giving them 7 days to respond if they'd like to stop this transfer, but otherwise this makes sense to give the project "new life" on PyPI.

**Comment by lazka** [comment]
Thanks for looking into this!

**Comment by lazka** [comment]
@ewdurbin Any news on this?

**Comment by ewdurbin** [comment]
@lazka transfer complete.

**Comment by lazka** [comment]
Thank you :)
