### ISSUE TITLE
Package rights for unoconv package

### ISSUE THREAD

**Issue by regebro** [pypa/pypi-legacy#735]
https://pypi.python.org/pypi/unoconv was created in 2015 by Shuge Lee, but unfortunately he doesn't seem to answer on the only email address I found, and only version 0.6 was uploaded, not later releases, and none of the unoconv maintainers have permissions. 

I would like the author of the package: dagwieers, or the maintainer (regebro, ie me) to get Owner rights to we can release a new version without naming conflict.

**Comment by ewdurbin** [comment]
@regebro, it does appear that this is an unfortunately common pattern of 3rd parties uploading a package to the index rather than the maintainers.

I've taken the following action:
  - notified the email address on file for the PyPI user of the situation
  - provided them with 7 days to respond

If we don't hear back after that, we'll proceed with transferring the package over to dagwieers.

**Comment by regebro** [comment]
Awesome!

**Comment by regebro** [comment]
Did you get any response?

**Comment by ewdurbin** [comment]
@regebro nope! we can wrap this up if @dagwieers can confirm a PyPI user they'd like this project transferred to.

**Comment by dagwieers** [comment]
@ewdurbin I am fine with transferring it to @regebro

**Comment by ewdurbin** [comment]
@regebro your PyPI username?

**Comment by regebro** [comment]
It's "regebro"

**Comment by ewdurbin** [comment]
Done.

**Comment by regebro** [comment]
Thanks!
