### ISSUE TITLE
Package in inconsistent state after deletion, than uploading

### ISSUE THREAD

**Issue by ethanhs** [pypa/pypi-legacy#740]
I decided to delete v0.0.1 of a project on pypi. I then uploaded a new version (I realize this is not all the preferred thing, and I apologize). The upload command returned 200s for both uploads. However, when I looked at my profile, nothing appeared. Furthermore, when I went to re-upload the files they were 400s, saying the filename was previously used. Could the files be uploaded but the project not created perhaps?

**Comment by ewdurbin** [comment]
@ethanhs PyPI username?

**Comment by ewdurbin** [comment]
@ethanhs, took a wild guess and checked the journals for the project it appears you were working on.

you’ve used the combination of the package name and file for versions `0.0.1` and `0.0.2` before deleting the project.

our index of filenames does not reset after deletion by design. you’ll need to start with a version that does not conflict with the above to reupload your package.

**Comment by ethanhs** [comment]
Ah, okay thanks!
