### ISSUE TITLE
rst rendering broken - no linters show any issues?

### ISSUE THREAD

**Issue by ctheune** [pypa/pypi-legacy#741]
I noticed that the long description wasn't rendered properly for a while now on my batou page:
https://pypi.python.org/pypi/batou/1.6.1 the same is on warehouse: https://pypi.org/project/batou/1.6.1/

I thought I spotted an rst error, but it wasn't. All the linters, docutils, setup.py check are not showing any errors at all. I'm at a loss here what I need to fix - especially as I can't make any experimental changes without adding releases to PyPI ... 

Help? @dstufft or @ewdurbin maybe? *hugs*

**Comment by jamadden** [comment]
I like using the [restview](https://pypi.python.org/pypi/restview) package for checking my long_description because it sees things exactly as PyPI does. 

If I download https://plan.flyingcircus.io/projects/batou/repository/changes/setup.py and https://plan.flyingcircus.io/projects/batou/repository/changes/CHANGES.txt and https://plan.flyingcircus.io/projects/batou/repository/changes/README (and rename the downloaded README.txt back to README, because something helpfully added a .txt extension) and then run `restview --long --pypi` it fails to render and reports the error: `<string>:171: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.` The error is in the very last entry in CHANGES.txt for 1.6.0a1, it's missing a leading space on the second line of the bullet.

**Comment by ewdurbin** [comment]
You can also use the very same codebase that is used to render your readme to check it!

See: https://github.com/pypa/readme_renderer#check-description-locally

**Comment by jamadden** [comment]
restview is build on readme-renderer 😄 It just adds convenient features like opening in a browser and auto-reloading when files change.
