### ISSUE TITLE
Claim package swordfish

### ISSUE THREAD

**Issue by tedwards2412** [pypa/pypi-legacy#742]
I have been trying to get my package [swordfish](http://github.com/cweniger/swordfish) to be installable via pip which I originally checked was available via a web search. When trying to upload the package I ran into the issue that the name has apparently already been registered. I found this out by following the advice from [this issue](https://github.com/pypa/pypi-legacy/issues/705). 

`
$ http https://pypi.python.org/simple/ | grep \'swordfish\'
<a href='swordfish'>swordfish</a><br/>
`

I have tried to contact the owner but have not been able to find any website or contact information anywhere associated with the name. I'd like to be able to take it over since it meets the required abandonment criteria laid out [here](https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project). I'm not sure even if the package was ever installable, it seems to just have been registered with no further action. We have been presenting the package to people within the community already with this name so it would be extremely useful if we could register it via pip.

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
