### ISSUE TITLE
Claim package name SpectroscoPy

### ISSUE THREAD

**Issue by lemmatum** [pypa/pypi-legacy#748]
The package name [spectroscopy](https://pypi.python.org/pypi/spectroscopy/0.10) is currently [unmaintained](https://github.com/jgoodknight/spectroscopy/pulse). I would like to claim the name for our general atomic spectroscopy package [SpectroscoPy](https://github.com/PlasmaPy/SpectroscoPy), which has significant ties to other physics packages such as [AstroPy](https://github.com/astropy/astropy) and [PlasmaPy](https://github.com/PlasmaPy/PlasmaPy).

I have attempted to contact the owner, @jgoodknight , but they are unresponsive.

**Comment by lemmatum** [comment]
Is there a set process for claiming package names or a minimum wait time?

**Comment by ewdurbin** [comment]
@lemmatum the larger issue is that there is _no_ process. [PEP 541](https://www.python.org/dev/peps/pep-0541/) aims to address this but it has not been accepted.

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
