### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by zhoupengyu823** [pypa/pypi-legacy#755]
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by jamadden** [comment]
Thank you for your report. I don't understand what you're trying to say though. Is that an error you get trying to connect to pypi.python.org? If it is, it's probably temporary and will go away on its own. If it's an error you get *using* some package downloaded and installed from PyPI, you'll need to contact the people that wrote that package because this issue tracker is only for issues with pypi.python.org itself.

**Comment by zhangysh1995** [comment]
@zhoupengyu823 This should be a networking error, please check your network connections first or try to use another network. You could also add a network agency.
