### ISSUE TITLE
Package Spam

### ISSUE THREAD

**Issue by webpigeon** [pypa/pypi-legacy#760]
Hello,
Sorry if this is the wrong place to report this but when I was testing the xml-rpc API I noticed the following packages in pypi, they appear to be spam:

- https://pypi.python.org/pypi/s11e12-Supernatural-Season-11-Episode-12-Links-updated/2.0
- https://pypi.python.org/pypi/hd-stream-supernatural-season-11-episode-12-dont-you-forget-about-me/1.1.9

**Comment by jamadden** [comment]
Thanks for the report! Those two packages do indeed seem to exist only to link to sites that promote (probably illegally) downloading copyrighted content, which then link to adware.

**Comment by di** [comment]
Thanks @webpigeon. I've deleted the projects. Please let us know if you find any more!

**Comment by ewdurbin** [comment]
https://github.com/pypa/pypi-legacy/commit/3b0539030c2a0ec2391d2129b5e5ef6b149638e9 removed the spammer friendly UI elements for registering a package, and both of these predate that change.

thanks for reporting indeed! did some goofing around with our internal journal to check for patterns that match these two spam packages but haven't found anything conclusive, looks to be an isolated instance of spamming rather than a wider pattern.

will close!
