### ISSUE TITLE
Claim package name fable

### ISSUE THREAD

**Issue by Anthchirp** [pypa/pypi-legacy#780]
This is [the entire existing package](https://pypi.python.org/pypi/fable):
```python
from distutils.core import setup

setup(name='fable', version='0.9', py_modules=['fable'])
```
No contact information in the package or for user [rppt](https://pypi.org/user/rppt/).

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
