### ISSUE TITLE
Claim package 'mlpack'

### ISSUE THREAD

**Issue by rcurtin** [pypa/pypi-legacy#793]
Hi there, this is in the same vein as #789.  I maintain the mlpack project (https://github.com/mlpack/mlpack), and we recently added Python bindings, but the name 'mlpack' is claimed so we were forced to take 'mlpack3'.  For our users it would be much easier if we could say 'pip install mlpack' instead of 'pip install mlpack3'.

I'd like to claim 'mlpack' under PEP 541, since I was not able to contact the package maintainer, and the package has seen no development or updates in many months.

I know the process is not ready yet, and I am not in a hurry, but I wanted to open this issue so that when the PEP 541 process is implemented, this can be handled.

Thanks!  (and of course let me know if any more information is needed)

**Comment by brainwane** [comment]
I'm sorry for the wait, and I thank you for your report.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
