### ISSUE TITLE
Claim package `xtermcolor`

### ISSUE THREAD

**Issue by ltworf** [pypa/pypi-legacy#798]
xtermcolor: https://github.com/broadinstitute/xtermcolor has been abandoned by the maintainer, last release is in 2015, and he has not accepted any pull request, replied to any bug or done any commit.

I am the debian maintainer of the package and I do have some commits in it, but I can't get more because I don't have write access on the repo.

I would like to get the name so I could be able to fork and keep compatibility.

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
