### ISSUE TITLE
Package in pypi not found when trying to install from pip command

### ISSUE THREAD

**Issue by nateshmbhat** [pypa/pypi-legacy#800]
My package by the name "webbot" is available in pypi but when I try to install it using pip , it's saying 
`Could not find a version that satisfies the requirement webbot (from versions: 0.0.1.win-amd64)` 

How do I fix it ?

**Comment by jamadden** [comment]
The `webbot` package on PyPI [lists two files](https://pypi.org/project/webbot/#files). One (webbot-0.0.1-py3-none-any.whl) is a binary wheel file that can only be installed with a recent version of pip on Python 3.

The other (webbot-0.0.1.win-amd64.zip) is a source distribution, but the version number portion (0.0.1.win-amd64) is either invalid and hence getting rejected, or specifies that the source is for a specific platform different than the one you're running on, and *also* getting rejected (honestly, I'm not sure if "platform tags" are allowed/respected in source distribution filenames).

So the fix is either to use a recent version of pip on Python 3, or to upload new wheels and source distributions with correct filenames and metadata.

Thanks for the report, but development on this repository has stopped and issues aren't usually monitored. PyPI is now handled by the https://github.com/pypa/warehouse project.
