### ISSUE TITLE
Claim package `magic`

### ISSUE THREAD

**Issue by zoulasc** [pypa/pypi-legacy#802]
Hi,

I am the owner/maintainer of the file(1) package for Unix which has python language bindings for libmagic(3). I distribute those bindings at:

    https://pypi.org/project/file-magic/

I have tried to contact "jpetrone" jp-py@jsnp.net who owns the "magic" package, but have gotten no response. The package seems abandoned (not updated since 2003). What do I need to do next to reclaim it?

Thanks,

christos

**Comment by jamadden** [comment]
The steps for abandoned projects are [outlined in PEP 541](https://www.python.org/dev/peps/pep-0541/#abandoned-projects).

**Comment by zoulasc** [comment]
Yes, so it is abandoned according to the criteria in PEP 541; the question is what do *I* need to do? I also sent mail to infrastructure-staff@python.org.

**Comment by brainwane** [comment]
I'm sorry for the wait.

We have archived this repository since it's about the legacy PyPI codebase. There's a new support ticket queue and I ask that, if you are still interested in this request, you [re-open your issue there](https://github.com/pypa/pypi-support/issues/new?labels=PEP+541&template=pep541-request.md&title=PEP+541+Request%3A+PROJECT_NAME) so we can follow up.

We're working on implementing PEP 541 with a new process -- you can subscribe to https://github.com/pypa/warehouse/issues/1506 to follow our progress. Once we do that, we'll start working through all the requests for package transfers within https://github.com/pypa/pypi-support/ .

Until then, unfortunately, all I can advise you to do is wait. My apologies.
