### ISSUE TITLE
xpra package points to unmaintained/abandoned version

### ISSUE THREAD

**Issue by ewdurbin** [pypa/pypi-legacy#83]
Originally reported by: **Antoine Martin (Bitbucket: [totaam](https://bitbucket.org/totaam), GitHub: [totaam](https://github.com/totaam))**
---

Some users have complained that they could not install the latest versions, ie:
http://lists.devloop.org.uk/pipermail/shifter-users/2013-October/000740.html

The version currently linked to has not been updated for over 3 years. It does not build properly, it does not run against any of the versions shipped by all the major distros. All said distros have switched to the "new upstream":
http://xpra.org/

Let me know if there is anything I need to do to help you update the link.
---
- Bitbucket: https://bitbucket.org/pypa/pypi/issue/83

**Comment by totaam** [comment]
That's almost 6 years now for the abandoned version on pypi...
Anything I can do to help move this along?

**Comment by berkerpeksag** [comment]
There isn't much we can do here as we don't actually maintain the package. I'd suggest contacting Nathaniel Smith <parti-discuss@partiwm.org> (found at https://pypi.org/project/xpra/) to take over the ownership of the package. If you can't get a response from them, you can open a support ticket at https://sourceforge.net/p/pypi/support-requests/

Closing this for now since this tracker is for issues with pypi.python.org itself. Thanks!
